name: Build DXVK

on: [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout DXVK
      uses: actions/checkout@v4
      with:
        repository: doitsujin/dxvk
        submodules: recursive
        fetch-depth: 0

    - name: Setup glslangValidator
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/HansKristian-Work/vkd3d-proton-ci/main/glslangValidator.exe" -OutFile "glslangValidator.exe"
        Write-Output "$pwd" | Out-File -FilePath "${Env:GITHUB_PATH}" -Append

    - name: Setup Meson
      shell: pwsh
      run: pip install meson

    - name: Find Visual Studio
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append

    - name: Download D3D8 SDK Headers
      shell: pwsh
      run: |
        Invoke-WebRequest -URI https://raw.githubusercontent.com/NovaRain/DXSDK_Collection/master/DXSDK_Aug2007/Include/d3d8.h -OutFile include/d3d8.h
        Invoke-WebRequest -URI https://raw.githubusercontent.com/NovaRain/DXSDK_Collection/master/DXSDK_Aug2007/Include/d3d8types.h -OutFile include/d3d8types.h
        Invoke-WebRequest -URI https://raw.githubusercontent.com/NovaRain/DXSDK_Collection/master/DXSDK_Aug2007/Include/d3d8caps.h -OutFile include/d3d8caps.h

    - name: Build MSVC ${{ matrix.arch }}
      shell: pwsh
      run: |
        $arch = if ("${{ matrix.arch }}" -eq "x86") { "x86" } else { "x64" }
        $host_arch = "x64"
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=$arch -host_arch=$host_arch -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson --buildtype release --backend vs2022 build-msvc-$arch
        msbuild -m build-msvc-$arch/dxvk.sln

    - name: Prepare artifacts for ${{ matrix.arch }}
      shell: pwsh
      run: |
        mkdir artifacts-${{ matrix.arch }}
        Get-ChildItem -Path build-msvc-${{ matrix.arch }}\src -Include *.dll,*.pdb -Recurse `
          | Copy-Item -Destination artifacts-${{ matrix.arch }}

    - name: Upload ${{ matrix.arch }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dxvk-${{ matrix.arch }}-dlls
        path: artifacts-${{ matrix.arch }}/
        if-no-files-found: error
